### ISSUE TITLE
Version 3.1.1 availability

### ISSUE THREAD

**Issue by tomikpik** [aws-greengrass/aws-greengrass-cloudwatch-metrics#10]
Hi,
I'd would like to update our production workload from Nucleus 2.7.x to 2.8.1 because the newer version fixes the problem we were experiencing before. 

The problem is that according to this link https://docs.aws.amazon.com/greengrass/v2/developerguide/cloudwatch-metrics-component.html

There should be a 3.1.1 version of Cloudwatch component that is compatible with the latest Nucleus.

However when we try to revise a deployment it gives us the message that the Cloudwatch version 3.1.1 is not available. 

According to this Github repo it also seems that there is no such version 3.1.1.

Can you please recommend Cloudwatch component version for nucleus 2.8.1 that we can deploy on our production workload as soon as possible?

Thank you
Tomas

**Comment by MikeDombo** [comment]
Hi Tomas,

What is the specific error that you're getting in the deployment? The most recent versions of all components do work together. You may be trying to deploy this component on an unsupported OS or CPU. Providing the actual error message will tell us what the problem is.

On Oct 19, 2022 8:46 AM, Tomas Pikous ***@***.***> wrote:

Hi,
I'd would like to update our production workload from Nucleus 2.7.x to 2.8.1 because the newer version fixes the problem we were experiencing before.

The problem is that according to this link https://docs.aws.amazon.com/greengrass/v2/developerguide/cloudwatch-metrics-component.html

There should be a 3.1.1 version of Cloudwatch component that is compatible with the latest Nucleus.

However when we try to revise a deployment it gives us the message that the Cloudwatch version 3.1.1 is not available.

According to this Github repo it also seems that there is no such version 3.1.1.

Can you please recommend Cloudwatch component version for nucleus 2.8.1 that we can deploy on our production workload as soon as possible?

Thank you
Tomas

**Comment by MikeDombo** [comment]
Hi Tomas,

Please use version 3.1.0. There is no version 3.1.1 that exists. I'll have the documentation addressed.
